export const carBrandsWithModels = {
  Abarth: ["500e", "595", "695", "124 Spider"],
  AC: [],
  Acura: ["Integra", "Integra Type S", "TLX", "RDX", "MDX", "ZDX", "ADX"],
  Afeela: [],
  Aion: ["V", "Y", "S", "LX", "Hyper SSR"],
  Aiways: ["U5", "U6", "U7"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "Junior", "33 Stradale"],
  Alpine: ["A110", "A110 R", "A290", "A390"],
  Aptera: [],
  Ariel: ["Atom 4", "Nomad 2"],
  Artega: ["Scalo Superelletra"],
  Ascari: [],
  "Aston Martin": ["DBX", "DBX707", "Vantage", "DB12", "Vanquish", "Valhalla"],
  Audi: [
    "A3",
    "A4",
    "A4 Allroad",
    "A5",
    "A6",
    "A6 e-tron",
    "A7",
    "A8",
    "S8",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q6 e-tron",
    "Q7",
    "Q8",
    "Q8 e-tron",
    "e-tron GT",
    "S3",
    "S4",
    "S5",
    "S6",
    "RS3",
    "RS5",
    "RS6 Avant",
    "RS Q3",
    "RS Q8",
  ],
  Austin: [],
  "Austin-Healey": [],
  "Auto Union": [],
  Autobianchi: [],
  BAIC: ["BJ40", "X55", "EU5", "BJ60", "X7"],
  Baojun: ["Yep", "Kiwi EV", "RS-5"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga", "Batur"],
  Benz: [],
  Bertone: [],
  Bestune: ["T77", "E01", "T99"],
  Bisu: ["T3", "T5"],
  Bizzarrini: [],
  BMW: [
    "1 Series",
    "2 Series",
    "2 Series Gran Coupe",
    "3 Series",
    "4 Series",
    "5 Series",
    "7 Series",
    "8 Series",
    "X1",
    "iX1",
    "X2",
    "X3",
    "iX3",
    "X4",
    "X5",
    "X6",
    "X7",
    "i4",
    "i5",
    "i7",
    "iX",
    "M2",
    "M3",
    "M4",
    "M5",
    "M5 Touring",
    "XM",
    "Z4",
  ],
  Borgward: [],
  Brabus: ["G-Class", "S-Class", "Rocket 1000"],
  Brilliance: ["V3", "V7"],
  Bristol: [],
  Bugatti: ["Chiron", "Mistral", "Bolide"],
  Buick: ["Enclave", "Encore GX", "Envista", "Envision"],
  BYD: [
    "Atto 3",
    "Dolphin",
    "Seal",
    "Han",
    "Tang",
    "Yuan Plus",
    "Song L",
    "Qin Plus",
  ],
  Byton: [],
  Cadillac: [
    "CT4",
    "CT5",
    "Escalade",
    "Escalade IQ",
    "Lyriq",
    "XT4",
    "XT5",
    "XT6",
    "Optiq",
    "Celestiq",
  ],
  Canoo: ["Lifestyle Vehicle", "MPD Van"],
  Caterham: ["Seven 275", "Seven 355", "Seven 485", "Seven 620R"],
  Changan: [
    "CS75",
    "UNI-K",
    "Eado",
    "CS55",
    "UNI-V",
    "Alsvin",
    "Oshan X7",
    "Karvaan",
    "M9",
  ],
  Chery: [
    "Tiggo 8",
    "Omoda 5",
    "Arrizo 8",
    "Tiggo 7",
    "Omoda 7",
    "Tiggo 4",
    "Tiggo 8 Pro",
  ],
  DFSK: ["Glory 500"],
  Chevrolet: [
    "Blazer",
    "Camaro",
    "Corvette",
    "Equinox",
    "Malibu",
    "Silverado",
    "Traverse",
    "Trax",
    "Equinox EV",
    "Blazer EV",
    "Bolt EUV",
    "Colorado",
    "Suburban",
    "Tahoe",
    "Express",
  ],
  Chrysler: ["Pacifica", "Pacifica Hybrid"],
  Citroën: [
    "C3",
    "C3 Aircross",
    "C4",
    "C5 Aircross",
    "Berlingo",
    "ë-C3",
    "ë-C4",
    "C5 X",
  ],
  Cupra: ["Formentor", "Born", "Leon", "Raval"],
  Dacia: ["Duster", "Sandero", "Jogger", "Spring"],
  Daewoo: [],
  Daihatsu: ["Rocky", "Taft", "Mira", "Hijet", "Copen"],
  Daimler: [],
  Datsun: [],
  DeLorean: [],
  Dodge: ["Charger", "Hornet", "Durango", "Charger Daytona"],
  Donkervoort: ["D8 GTO"],
  DS: ["DS 3", "DS 4", "DS 7", "DS 9"],
  Eagle: [],
  Exeed: ["TXL", "VX", "RX"],
  "Faraday Future": ["FF 91"],
  Ferrari: ["Purosangue", "Roma", "SF90", "296 GTB", "12Cilindri", "F80"],
  Fiat: ["500", "500e", "Panda", "Tipo", "600", "Strada", "Pulse"],
  Fisker: ["Ocean"],
  Ford: [
    "Bronco",
    "Bronco Sport",
    "Escape",
    "Edge",
    "Explorer",
    "Expedition",
    "F-150",
    "Mustang",
    "Maverick",
    "Ranger",
    "Transit",
    "Mustang Mach-E",
    "F-150 Lightning",
  ],
  Foton: ["Tunland", "Sauvana"],
  GAC: ["GS8", "Aion S", "GS4", "Trumpchi M8"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80", "GV60 Magma"],
  Geely: ["Coolray", "Monjaro", "Preface", "Galaxy L7"],
  GMC: ["Canyon", "Sierra", "Terrain", "Yukon", "Hummer EV", "Sierra EV"],
  "Great Wall": [
    "Haval H6",
    "Haval Jolion",
    "Tank 300",
    "Tank 500",
    "Pao",
    "Ora 03",
    "Ora 07",
  ],
  Hennessey: ["Venom F5"],
  Hino: ["Series 300", "Series 500", "Series 700"],
  Holden: [],
  Hongqi: ["H5", "H9", "E-HS9", "E-QM5"],
  Hummer: ["Hummer EV Pickup", "Hummer EV SUV"],
  Hyundai: [
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Ioniq 5",
    "Ioniq 6",
    "Ioniq 9",
    "Kona",
    "Venue",
    "Nexo",
    "Santa Cruz",
  ],
  IAME: [],
  Infiniti: ["Q50", "QX50", "QX55", "QX60", "QX80"],
  Ineos: ["Grenadier", "Quartermaster", "Fusilier"],
  Innoson: ["IVM Umu", "IVM Uzo"], 
  Iveco: ["Daily", "Eurocargo"],
  Jaguar: ["F-Pace", "E-Pace", "I-Pace", "F-Type"],
  Jaecoo: ["J7", "J8"], // New brand
  Jeep: [
    "Compass",
    "Cherokee",
    "Grand Cherokee",
    "Wrangler",
    "Gladiator",
    "Wagoneer",
    "Wagoneer S",
  ],
  Jensen: [],
  Jetour: ["X70", "Dashing", "X90"],
  JMC: ["Vigus", "Yuhu"],
  Karma: ["Revero", "Gspera"],
  Koenigsegg: ["Jesko", "Regera", "CC850"],
  KTM: ["X-Bow"],
  Lada: ["Vesta", "Granta", "Niva"],
  Lamborghini: ["Huracan", "Urus", "Revuelto", "Revuelto SVJ"],
  Lancia: ["Ypsilon"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Range Rover",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Landwind: [],
  Lexus: ["ES", "IS", "NX", "RX", "TX", "RZ", "UX"],
  "Li Auto": ["L7", "L9", "L6"],
  Lincoln: ["Aviator", "Corsair", "Nautilus", "Navigator"],
  Lonsdale: [],
  Lotus: ["Emira", "Evija", "Eletre", "Emeya"],
  Lucid: ["Air", "Gravity"],
  "Lynk & Co": ["01", "03", "08"],
  Mahindra: [
    "XUV700",
    "Scorpio",
    "Thar",
    "BE 6",
    "Bolero",
    "Bolero Neo",
    "XUV 3XO",
  ],
  Maserati: [
    "Grecale",
    "Levante",
    "Quattroporte",
    "Ghibli",
    "GranTurismo",
    "GranCabrio",
  ],
  Maybach: ["S-Class", "GLS"],
  Mazda: [
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-70",
    "CX-90",
    "Mazda3",
    "MX-5",
    "CX-3",
    "Mazda6",
  ],
  McLaren: ["Artura", "750S", "GT", "Senna"],
  "Mercedes-Benz": [
    "C-Class",
    "E-Class",
    "S-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "EQB",
    "EQE",
    "EQS",
    "G-Class",
    "EQG",
    "GLC350e",
    "AMG GT",
  ],
  Mercury: [],
  Mini: ["Cooper", "Countryman", "Clubman", "Aceman"],
  Mitsubishi: ["Outlander", "Eclipse Cross", "ASX", "Triton"],
  Morgan: ["Plus Four", "Plus Six", "Super 3"],
  Moskvitch: ["3", "6"],
  Neta: ["V", "U", "S", "Aya", "X"], // New brand
  NIO: ["ET5", "ET7", "ES8", "EC6"],

  Nissan: [
    "Note",
    "X Trail",
    "Leaf",
    "Juke",
    "Dayz",
  ],
  Oldsmobile: [],
  Opel: ["Corsa", "Astra", "Mokka", "Grandland", "Crossland", "Combo Life"],
  Pagani: ["Huayra", "Utopia", "Huayra BC"],
  Panoz: [],
  Perodua: ["Myvi", "Bezza", "Aruz", "Alza", "Axia"], // New brand (Malaysia)
  Peugeot: [
    "208",
    "308",
    "2008",
    "3008",
    "5008",
    "408",
    "508",
    "e-208",
    "e-2008",
  ],
  Pininfarina: ["Battista"],
  Plymouth: [],
  Polestar: ["2", "3", "4", "5", "6"],
  Pontiac: [],
  Porsche: [
    "911",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
    "718 Boxster",
    "718 Cayman",
    "Taycan Cross Turismo",
  ],
  Proton: ["Saga", "X50", "X70", "X90", "S70"], // Expanded from original
  Ram: ["1500", "2500", "3500", "Rampage", "ProMaster"],
  Renault: [
    "Captur",
    "Clio",
    "Megane",
    "Austral",
    "5",
    "Twingo",
    "Arkana",
    "Scenic",
    "Espace",
  ],
  Volkswagen: [
    "Golf",
    "Tiguan",
    "Atlas",
    "Jetta",
    "ID.4",
    "ID. Buzz",
    "Passat",
    "Taos",
    "T-Roc",
    "ID.3",
    "Polo",
    "T-Cross",
  ],
  Volvo: ["XC40", "XC60", "XC90", "S60", "EX30", "EX90", "S90", "V60", "V90"],
  Voyah: ["Free", "Dream", "Zhuiguang"],
  Wey: ["Coffee 01", "Coffee 02", "Mocha"], // New brand (China)
  Wiesmann: ["Project Thunderball"],
  Wuling: ["Hongguang Mini EV", "Bingo", "Airev", "Starlight"],
  Xpeng: ["P7", "G9", "P5", "G6"],
  Zastava: [],
  Zeekr: ["001", "X", "009", "007", "CX1e"],
  Haval: ["Jolion", "Dargo", "H9", "H6"],
  Honda: [
    "Vezel",
    "Fit",
    "Accord",
    "Civic",
    "CR-V",
    "HR-V",
    "Pilot",
    "Prologue",
    "ZR-V",
    "Prelude",
    "City",
    "BR-V",
  ],
  Hyundai: [
    "Elantra",
    "Sonata",
    "Tucson",
    "Tucson Hybrid",
    "Santa Fe",
    "Palisade",
    "Ioniq 5",
    "Ioniq 6",
    "Ioniq 9",
    "Kona",
    "Venue",
    "Nexo",
    "Santa Cruz",
  ],
  Kia: [
    "Sportage",
    "EV5",
    "K4",
    "Picanto",
  ],
  MG: ["4", "5", "ZS", "ZS EV", "HS", "Cyberster"],
  Suzuki: [
    "Baleno",
    "Celerio",
    "Celerio X",
    "Dzire",
    "Ertiga",
    "Ignis",
    "Mehran",
    "FX",
    "Liana",
    "Swift",
    "Vitara",
    "Jimny",
    "Fronx",
    "Alto",
    "Cultus",
    "Wagon R",
    "Bolan",
    "Ravi",
  ],
  Toyota: [
    "Prado V8",
    "Prado V6",
    "Camry",
    "Aqua",
    "Corolla",
    "RAV4",
    "Highlander",
    "Tacoma",
    "Tundra",
    "Prius",
    "4Runner",
    "Land Cruiser",
    "bZ4X",
    "Sienna",
    "Corolla Cross",
    "Grand Highlander",
    "Crown",
    "Sequoia",
    "Yaris Cross",
    "GR86",
    "Supra",
    "Fortuner",
    "Hilux",
    "Vitz",
    "Yaris",
  ],
};
